[package]
name = "model_generation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
askama_derive = "0.12.1"
csv = "1.2.2"
serde = { version = "1.0", features = ["derive"] }
